# Default yml file for running Traefik.
#
# ~NETWORK_LIST~ will be replaced by list of networks.
# ~NETWORK_SECTION~ will be replaced by proper networks section.
#
# You may copy this file to traefik-helper.default.yml and add or replace items
# as desired. Make sure to keep both networks sections in place with tokens.

version: '2'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    networks:
~NETWORK_LIST~
    ports:
      - '80:80'
      - '8080:8080'
      - '8025:8025'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
~NETWORK_SECTION~
